version: '3'
services:
  web:
    image: socle_angular
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - NODE_VERSION=${NODEJS}
      - NGCLI_VERSION=${NGCLI}
      - HTTP_PORT=${HTTP_CONTAINER}
      - HTTPS_PORT=${HTTPS_CONTAINER}
      - KARMA_PORT=${KARMA_CONTAINER}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HTTP_LOCAL}:${HTTP_CONTAINER}"
      - "${HTTPS_LOCAL}:${HTTPS_CONTAINER}"
      - "${KARMA_LOCAL}:${KARMA_CONTAINER}"
    # depends_on:
    #  - jsonserver
    volumes:
      - ./:/app
      - /usr/src/app/node_modules
  # jsonserver:
    # image: jsonserver
    # restart: always
    # build: .
    # container_name: jsonserver_mock-dev
    # ports:
    #  - "3000:3000"
    tty: true